name: CI/CD

on: [push, pull_request, workflow_dispatch]

env:
  DOCKERHUB_USERNAME: suniastar

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2.4.0

      - name: Setup Java JDK
        uses: actions/setup-java@v2.4.0
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Gradle Build
        uses: gradle/gradle-build-action@v2.0.1

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: logldap
          path: logldap/build/libs/scan-log4shell-logldap-*

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: build
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2.4.0

      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: logldap
          path: logldap/

      - name: Build Docker image
        run: |
          docker pull ${{ matrix.base }}/openjdk-17:slim
          docker build \
            --pull \
            --build-arg ARCH=${{ matrix.base }} \
            --label "org.opencontainers.image.created=$(date --rfc-3339=seconds)" \
            --label "org.opencontainers.image.authors=Frederik Enste <frederik@fenste.de>, kost <https://github.com/kost>" \
            --label "org.opencontainers.image.url=https://github.com/suniastar/scan-log4shell" \
            --label "org.opencontainers.image.source=https://github.com/suniastar/scan-log4shell.git" \
            --label "org.opencontainers.image.version=0.1" \
            --label "org.opencontainers.image.vendor=suniastar" \
            --label "org.opencontainers.image.title=LogLDAP" \
            --label "org.opencontainers.image.description=A mock LDAP server that locks incomming requests." \
            --label "org.opencontainers.image.base.name=${{ matrix.base }}/alpine:latest" \
            --label  org.opencontainers.image.base.digest=$(docker image inspect ${{ matrix.base }}/openjdk-17:slim | grep -o 'Id": "[a-z0-9:]*' | sed 's/Id": "//g') \
            --tag "${DOCKERHUB_USERNAME}/logldap:latest" \
            ./logldap

      - name: Upload Docker image
        run: docker push "${{ env.DOCKERHUB_USERNAME }}/logldap:latest"
